options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: "gcr.io/cloud-builders/docker"
    id: Build Image
    args:
      [
        "build",
        "-t",
        "northamerica-northeast1-docker.pkg.dev/off-net-dev/cloud-security/hello-world:$TAG_NAME",
        ".",
      ]

  - name: "gcr.io/cloud-builders/docker"
    id: Push Image
    args:
      [
        "push",
        "northamerica-northeast1-docker.pkg.dev/off-net-dev/cloud-security/hello-world:$TAG_NAME",
      ]

  - name: "gcr.io/cloud-builders/gcloud"
    id: Deploy to GKE
    entrypoint: bash
    env:
      - "TAG_NAME=$TAG_NAME"
    args:
      - "-c"
      - |
        if [[ -z "$TAG_NAME" || "$TAG_NAME" == "latest" ]]; then
          echo "Invalid TAG_NAME: '$TAG_NAME'. Aborting deployment."
          exit 1
        fi

        echo "Installing envsubst..."
        apt-get update -qq && apt-get install -y gettext

        echo "Rendering manifest with tag $TAG_NAME..."
        envsubst < k8s-deployment.yaml.template > final.yaml

        gcloud container clusters get-credentials hello-world-cluster --region northamerica-northeast1

        kubectl apply -f final.yaml --wait

images:
  - "northamerica-northeast1-docker.pkg.dev/off-net-dev/cloud-security/hello-world:$TAG_NAME"
