options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: "gcr.io/cloud-builders/docker"
    id: Build Image
    args:
      [
        "build",
        "-t",
        "northamerica-northeast1-docker.pkg.dev/off-net-dev/cloud-security/hello-world:$TAG_NAME",
        ".",
      ]

  - name: "gcr.io/cloud-builders/docker"
    id: Push Image
    args:
      [
        "push",
        "northamerica-northeast1-docker.pkg.dev/off-net-dev/cloud-security/hello-world:$TAG_NAME",
      ]

  - name: "gcr.io/cloud-builders/gcloud"
    id: Deploy to GKE
    entrypoint: bash
    args:
      - "-c"
      - |
        if [[ -z "$TAG_NAME" || "$TAG_NAME" == "latest" ]]; then
          echo "Invalid TAG_NAME: '$TAG_NAME'. Aborting deployment."
          exit 1
        fi

        echo "Deploying tag $TAG_NAME..."

        # Replace placeholder with actual tag
        sed "s|northamerica-northeast1-docker.pkg.dev/off-net-dev/cloud-security/hello-world:TAG|northamerica-northeast1-docker.pkg.dev/off-net-dev/cloud-security/hello-world:$TAG_NAME|g" k8s-deployment.yaml > final.yaml

        # Get cluster credentials
        gcloud container clusters get-credentials hello-world-cluster --region northamerica-northeast1

        # Apply the manifest with rollout tracking
        kubectl apply -f final.yaml --record --wait

images:
  - "northamerica-northeast1-docker.pkg.dev/off-net-dev/cloud-security/hello-world:$TAG_NAME"
